services:
  email_api:
    image: python:3.12-slim
    container_name: email-api
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - pip-cache:/root/.cache/pip
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8083"
    ports:
      - "8083:8083"

  email_consumer:
    image: python:3.12-slim
    container_name: email-consumer
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - pip-cache:/root/.cache/pip
    command: >
      sh -c "pip install -r requirements.txt &&
             python -m consumer.consumer"

volumes:
  pip-cache:
